-- MySQL Script generated by MySQL Workbench
-- Fri May 19 16:35:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exampleDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exampleDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exampleDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `exampleDB` ;

-- -----------------------------------------------------
-- Table `exampleDB`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exampleDB`.`person` (
  `person_id` INT NOT NULL,
  `birth_date` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`person_id`),
  UNIQUE INDEX `person_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exampleDB`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exampleDB`.`picture` (
  `picture_id` INT NOT NULL AUTO_INCREMENT,
  `picture_data` MEDIUMBLOB NOT NULL,
  `picture_file` VARCHAR(255) NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`picture_id`),
  INDEX `picture_fk_person` (`person_id` ASC) VISIBLE,
  CONSTRAINT `picture_fk_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `exampleDB`.`person` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exampleDB`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exampleDB`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `post_text` VARCHAR(500) NULL DEFAULT NULL,
  `person_id` INT NOT NULL,
  `picture_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `post_fk_person` (`person_id` ASC) VISIBLE,
  INDEX `post_fk_picture` (`picture_id` ASC) VISIBLE,
  CONSTRAINT `post_fk_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `exampleDB`.`person` (`person_id`),
  CONSTRAINT `post_fk_picture`
    FOREIGN KEY (`picture_id`)
    REFERENCES `exampleDB`.`picture` (`picture_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exampleDB`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exampleDB`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_text` VARCHAR(255) NOT NULL,
  `person_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `comment_fk_person` (`person_id` ASC) VISIBLE,
  INDEX `comment_fk_post` (`post_id` ASC) VISIBLE,
  CONSTRAINT `comment_fk_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `exampleDB`.`person` (`person_id`),
  CONSTRAINT `comment_fk_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `exampleDB`.`post` (`post_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exampleDB`.`friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exampleDB`.`friend` (
  `person1_id` INT NOT NULL,
  `person2_id` INT NOT NULL,
  PRIMARY KEY (`person1_id`, `person2_id`),
  INDEX `friend2_fk_person` (`person2_id` ASC) VISIBLE,
  CONSTRAINT `friend1_fk_person`
    FOREIGN KEY (`person1_id`)
    REFERENCES `exampleDB`.`person` (`person_id`),
  CONSTRAINT `friend2_fk_person`
    FOREIGN KEY (`person2_id`)
    REFERENCES `exampleDB`.`person` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `exampleDB`.`person_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exampleDB`.`person_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
